## 2.4 QR-разложение
**При написании программы нельзя использовать готовые функции для матричного умножения и обращения матриц кроме случаев, когда это явно описано.**

Напишите программу для решения системы $Ax = b$ методом наименьших квадратов с помощью $QR$-разложения Требования к программе:
1. Программа должна содержать функцию, принимающую на вход матрицу A и вектор правой части b.
2. Функция должна сначала вычислять $QR$-разложение матрицы $A \in \mathbb{C}^{m \times n}, m \geqslant n$ с помощью модифицированного алгоритма Грамма-Шмидта.
3. После вычисления $QR$-разложения нужно решить систему методом наименьших квадратов. **Для умножения на матрицу $Q^T$ можно использовать готовую функцию.** Для решения системы с треугольной матрицей R нужно реализовать метод обратной подстановки.
4. Функция должна возвращать матрицы $Q, R$ и вектор решения $x$.
5. Программа должна вызывать реализованную функцию для
  a. квадратной невырожденной матрицы
  b. прямоугольной матрицы c $m > n$ с линейно независимыми столбцами
из стандартных функций (например, `numpy.linalg.solve`, `numpy.linalg.lstsq`)

In [1]:
import numpy as np
np.warnings.filterwarnings("ignore")

def qr_solve(A, b):
    # QR-decomposition
    P = np.zeros(A.shape)
    Q = np.zeros(A.shape)
    R = np.zeros((A.shape[1], A.shape[1]))
    for j in range(A.shape[1]):
        P[:,j] = A[:,j]
        for i in range(j):
            R[i,j] = np.dot(P[:,j],Q[:,i])
            P[:,j] = P[:,j] - Q[:,i]*R[i,j]
        R[j,j] = np.linalg.norm(P[:,j])
        Q[:,j] = P[:,j] / R[j,j]
    # Finding y = Q*b for Rx = Q*b
    y = Q.T @ b
    # Finding solution x for Rx = y
    x = np.zeros(A.shape[1])
    for i in range(len(x) - 1, -1, -1):
        x[i] = y[i]
        for j in range(i + 1, len(x)):
            x[i] = x[i] - R[i,j]*x[j]
        x[i] = x[i] / R[i,i]
    return Q, R, x
    
# Testing
n = 4
A = np.random.rand(n,n)
b = np.random.rand(n)
print(A)
A = A + np.eye(n)
Q, R, x = qr_solve(A, b)
print("My QR-decomposition method: x = ", x)
x_1 = np.linalg.solve(A, b)
print("Built-in function: x = ", x_1)

m, n = 7, 4
A = np.random.rand(m,n)
for i in range(n):
    x = np.zeros(m)
    x[i] = 1
    A[:,i] = A[:,i] + x
b = np.random.rand(m)
Q, R, x = qr_solve(A, b)
print("My QR-decomposition method: x = ", x)
x_1 = np.linalg.lstsq(A, b)
print("Built-in function: x = ", x_1[0])

[[0.97411295 0.87419282 0.50046546 0.25647997]
 [0.89916723 0.08399249 0.86084681 0.58584591]
 [0.29218397 0.7170761  0.76481058 0.00745817]
 [0.25676587 0.25610749 0.86803926 0.06200503]]
My QR-decomposition method: x =  [0.00481067 0.17626418 0.0712984  0.74754735]
Built-in function: x =  [0.00481067 0.17626418 0.0712984  0.74754735]
My QR-decomposition method: x =  [-0.01058508  0.45886965  0.26151499  0.0461313 ]
Built-in function: x =  [-0.01058508  0.45886965  0.26151499  0.0461313 ]
